
dubbo:
  application:
    name: day2-zchao-web # 指定当前服务名，不能重复
  registry:
    address: 127.0.0.1:2181 # 指定注册中心
    protocol: zookeeper
  monitor:
    protocol: registry # 连接监控中心
server:
  port: 8081 # 因为监控中心端口是8080所以把tomcat改为8081