dubbo:
  application:
    name: day2-zchao-service # 指定当前服务名，不能重复
  registry:
    address: 127.0.0.1:2181 # 指定注册中心
    protocol: zookeeper
  protocol:
    name: dubbo # 指定通信规则 通信协议，通信端口
    port: 20080
  monitor:
    protocol: registry # 连接监控中心
#  scan:
#    base-packages: cn.zcclj.dubbo.impl   # 在入口加了@EnableDubbo注解就不需要这个包扫描